# Generated by Django 6.1 on 2026-08-29 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoLeadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_generator', models.CharField(max_length=150)),
                ('client_partner_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city_location', models.CharField(blank=True, max_length=150, null=True)),
                ('business_type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('OneS Academy', 'OneS Academy')], max_length=30)),
                ('lead_source', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
    ]
