# Generated by Django 6.1 on 2026-09-05 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoLeadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('lead_source', models.CharField(choices=[('None', 'None'), ('Advertisement', 'Advertisement'), ('Cold Call', 'Cold Call'), ('Employee Referral', 'Employee Referral'), ('External Referral', 'External Referral'), ('Online Store', 'Online Store'), ('Partner', 'Partner'), ('Public Relations', 'Public Relations'), ('Sales Email Alias', 'Sales Email Alias'), ('Seminar Partner', 'Seminar Partner'), ('Internal Seminar', 'Internal Seminar'), ('Trade Show', 'Trade Show'), ('Web Download', 'Web Download'), ('Web Research', 'Web Research'), ('Chat', 'Chat'), ('X (Twitter)', 'X (Twitter)'), ('Facebook', 'Facebook')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
    ]
