# Generated by Django 6.1 on 2026-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoleadmodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='annual_revenue',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='industry',
            field=models.CharField(choices=[('None', 'None'), ('ASP (Application Service Provider)', 'ASP (Application Service Provider)'), ('Data/Telecom OEM', 'Data/Telecom OEM'), ('ERP (Enterprise Resource Planning)', 'ERP (Enterprise Resource Planning)'), ('Government/Military', 'Government/Military'), ('Large Enterprise', 'Large Enterprise'), ('Management', 'Management'), ('ISV', 'ISV'), ('MSP (Management Service Provider)', 'MSP (Management Service Provider)'), ('Network Equipment Enterprise', 'Network Equipment Enterprise'), ('Non-management ISV', 'Non-management ISV'), ('Optical Networking', 'Optical Networking'), ('Service Provider', 'Service Provider'), ('Small/Medium Enterprise', 'Small/Medium Enterprise'), ('Storage Equipment', 'Storage Equipment'), ('Storage Service Provider', 'Storage Service Provider'), ('Systems Integrator', 'Systems Integrator'), ('Wireless Industry', 'Wireless Industry'), ('ERP', 'ERP'), ('Management ISV', 'Management ISV')], default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='lead_status',
            field=models.CharField(choices=[('None', 'None'), ('Attempted to Contact', 'Attempted to Contact'), ('Contact in Future', 'Contact in Future'), ('Contacted', 'Contacted'), ('Junk Lead', 'Junk Lead'), ('Lost Lead', 'Lost Lead'), ('Not Contacted', 'Not Contacted'), ('Pre-Qualified', 'Pre-Qualified'), ('Not Qualified', 'Not Qualified')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='rating',
            field=models.CharField(choices=[('None', 'None'), ('Acquired', 'Acquired'), ('Active', 'Active'), ('Market Failed', 'Market Failed'), ('Project Cancelled', 'Project Cancelled'), ('Shut Down', 'Shut Down')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
