# Generated by Django 6.1 on 2026-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_djangoleadmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoleadmodel',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djangoleadmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='djangoleadmodel',
            name='lead_source',
            field=models.CharField(choices=[('None', 'None'), ('Advertisement', 'Advertisement'), ('Cold Call', 'Cold Call'), ('Employee Referral', 'Employee Referral'), ('External Referral', 'External Referral'), ('Online Store', 'Online Store'), ('Partner', 'Partner'), ('Public Relations', 'Public Relations'), ('Sales Email Alias', 'Sales Email Alias'), ('Seminar Partner', 'Seminar Partner'), ('Internal Seminar', 'Internal Seminar'), ('Trade Show', 'Trade Show'), ('Web Download', 'Web Download'), ('Web Research', 'Web Research'), ('Chat', 'Chat'), ('X (Twitter)', 'X (Twitter)'), ('Facebook', 'Facebook')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='djangoleadmodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
