# Generated by Django 6.1 on 2026-09-14 12:18

import django.db.models.deletion
import src.modules.tasks.domain.enums.task_priority
import src.modules.tasks.domain.enums.task_status
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0003_djangocontactmodel_is_deleted'),
        ('leads', '0003_djangoleadmodel_is_converted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoTaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Highest', 'Highest'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low'), ('Lowest', 'Lowest')], default=src.modules.tasks.domain.enums.task_priority.TaskPriority['NORMAL'], max_length=100)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Deferred', 'Deferred'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Waiting for Input', 'Waiting for Input')], default=src.modules.tasks.domain.enums.task_status.TaskStatus['NOT_STARTED'], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounts.djangoaccountmodel')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='contacts.djangocontactmodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='leads.djangoleadmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
