# Generated by Django 6.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0002_remove_djangomeetingparticipantmodel_meeting_participant_type_match_and_more"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoReminderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("remind_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="meetings.djangomeetingmodel",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="tasks.djangotaskmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminders",
                "indexes": [
                    models.Index(fields=["user", "remind_at"], name="reminders_user_id_1c0e7f_idx"),
                    models.Index(fields=["remind_at"], name="reminders_remind_8eeb0a_idx"),
                    models.Index(fields=["task"], name="reminders_task_id_6d6f2f_idx"),
                    models.Index(fields=["meeting"], name="reminders_meetin_1d5a4b_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(meeting__isnull=True) | models.Q(task__isnull=True),
                        name="reminder_single_target",
                    ),
                ],
            },
        ),
    ]
