# Generated by Django 6.1 on 2026-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=30),
        ),
    ]
