# Generated by Django 6.1 on 2026-09-08 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoContactModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('other_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('assistant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('assistant', models.CharField(blank=True, max_length=255, null=True)),
                ('email_opt_out', models.BooleanField(default=False)),
                ('mailing_address', models.CharField(blank=True, max_length=500, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('other_address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='accounts.djangoaccountmodel')),
                ('contact_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_contacts', to=settings.AUTH_USER_MODEL)),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='contacts.djangocontactmodel')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
