# Generated by Django 6.1 on 2026-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_djangocontactmodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangocontactmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
