# Generated by Django 6.1

import django.db.models.deletion
import src.modules.meetings.domain.enums.meeting_participant_type
import src.modules.meetings.domain.enums.meeting_related_record_type
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0003_djangocontactmodel_is_deleted"),
        ("leads", "0003_djangoleadmodel_is_converted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoMeetingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_all_day", models.BooleanField(default=False)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meetings",
            },
        ),
        migrations.CreateModel(
            name="DjangoMeetingParticipantModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("LEAD", "LEAD"),
                            ("USER", "USER"),
                            ("CONTACT", "CONTACT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_participants",
                        to="contacts.djangocontactmodel",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_participants",
                        to="leads.djangoleadmodel",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="meetings.djangomeetingmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_participants",
                "indexes": [
                    models.Index(
                        fields=["meeting", "participant_type"],
                        name="mtg_part_type_idx",
                    ),
                    models.Index(
                        fields=["participant_type"],
                        name="mtg_participant_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            Q(participant_type="LEAD")
                            & Q(contact__isnull=True)
                            & Q(lead__isnull=False)
                            & Q(user__isnull=True)
                        )
                        | (
                            Q(participant_type="USER")
                            & Q(contact__isnull=True)
                            & Q(lead__isnull=True)
                            & Q(user__isnull=False)
                        )
                        | (
                            Q(participant_type="CONTACT")
                            & Q(contact__isnull=False)
                            & Q(lead__isnull=True)
                            & Q(user__isnull=True)
                        ),
                        name="meeting_participant_type_match",
                    ),
                    models.UniqueConstraint(
                        fields=("meeting", "lead"),
                        name="unique_meeting_participant_lead",
                    ),
                    models.UniqueConstraint(
                        fields=("meeting", "user"),
                        name="unique_meeting_participant_user",
                    ),
                    models.UniqueConstraint(
                        fields=("meeting", "contact"),
                        name="unique_meeting_participant_contact",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DjangoMeetingRelatedRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("LEAD", "LEAD"), ("CONTACT", "CONTACT")],
                        max_length=20,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_related_records",
                        to="contacts.djangocontactmodel",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_related_records",
                        to="leads.djangoleadmodel",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_records",
                        to="meetings.djangomeetingmodel",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_related_records",
                "indexes": [
                    models.Index(
                        fields=["meeting", "record_type"],
                        name="mtg_rel_type_idx",
                    ),
                    models.Index(
                        fields=["record_type"],
                        name="mtg_rel_record_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            Q(record_type="LEAD")
                            & Q(contact__isnull=True)
                            & Q(lead__isnull=False)
                        )
                        | (
                            Q(record_type="CONTACT")
                            & Q(contact__isnull=False)
                            & Q(lead__isnull=True)
                        ),
                        name="meeting_related_record_type_match",
                    ),
                    models.UniqueConstraint(
                        fields=("meeting", "lead"),
                        name="unique_meeting_related_lead",
                    ),
                    models.UniqueConstraint(
                        fields=("meeting", "contact"),
                        name="unique_meeting_related_contact",
                    ),
                ],
            },
        ),
    ]
