# Generated by Django 6.1 on 2026-09-25 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_djangocontactmodel_is_deleted'),
        ('leads', '0003_djangoleadmodel_is_converted_and_more'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='djangomeetingparticipantmodel',
            name='meeting_participant_type_match',
        ),
        migrations.RemoveConstraint(
            model_name='djangomeetingrelatedrecordmodel',
            name='meeting_related_record_type_match',
        ),
        migrations.RenameIndex(
            model_name='djangomeetingparticipantmodel',
            new_name='meeting_par_meeting_e28c5b_idx',
            old_name='mtg_part_type_idx',
        ),
        migrations.RenameIndex(
            model_name='djangomeetingparticipantmodel',
            new_name='meeting_par_partici_5d58ae_idx',
            old_name='mtg_participant_idx',
        ),
        migrations.RenameIndex(
            model_name='djangomeetingrelatedrecordmodel',
            new_name='meeting_rel_meeting_170df7_idx',
            old_name='mtg_rel_type_idx',
        ),
        migrations.RenameIndex(
            model_name='djangomeetingrelatedrecordmodel',
            new_name='meeting_rel_record__5193fd_idx',
            old_name='mtg_rel_record_idx',
        ),
        migrations.AddIndex(
            model_name='djangomeetingmodel',
            index=models.Index(fields=['is_deleted'], name='meetings_is_dele_b72e10_idx'),
        ),
        migrations.AddIndex(
            model_name='djangomeetingmodel',
            index=models.Index(fields=['start_at'], name='meetings_start_a_e5463c_idx'),
        ),
        migrations.AddIndex(
            model_name='djangomeetingmodel',
            index=models.Index(fields=['end_at'], name='meetings_end_at_244aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='djangomeetingmodel',
            index=models.Index(fields=['host'], name='meetings_host_id_e8c02e_idx'),
        ),
        migrations.AddConstraint(
            model_name='djangomeetingparticipantmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participant_type', 'LEAD'), ('lead__isnull', False), ('user__isnull', True), ('contact__isnull', True)), models.Q(('participant_type', 'USER'), ('user__isnull', False), ('lead__isnull', True), ('contact__isnull', True)), models.Q(('participant_type', 'CONTACT'), ('contact__isnull', False), ('lead__isnull', True), ('user__isnull', True)), _connector='OR'), name='meeting_participant_type_match'),
        ),
        migrations.AddConstraint(
            model_name='djangomeetingrelatedrecordmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record_type', 'LEAD'), ('lead__isnull', False), ('contact__isnull', True)), models.Q(('record_type', 'CONTACT'), ('contact__isnull', False), ('lead__isnull', True)), _connector='OR'), name='meeting_related_record_type_match'),
        ),
    ]
