from enum import Enum


class UserAuditAction(str, Enum):
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_BLOCKED = "USER_BLOCKED"
    USER_UNBLOCKED = "USER_UNBLOCKED"
    USER_PASSWORD_RESET = "USER_PASSWORD_RESET"
    USER_RETIRED = "USER_RETIRED"
